DROP TABLE IF EXISTS user_stage_progress CASCADE;
DROP TABLE IF EXISTS task_groups CASCADE;
DROP TABLE IF EXISTS task_stages CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS group_players CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS pgn_games CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
