server {
    listen 80 default_server;
    server_name _;
    root /var/www/html/public;
    index index.php;

    client_max_body_size 16M;

    resolver 127.0.0.11 valid=10s ipv6=off;

    location / {
        try_files $uri $uri/ /index.php?_url=$uri&$args;
    }

    location ~ \.php$ {
        set $upstream_backend "backend:9000";
        fastcgi_pass $upstream_backend;
        fastcgi_index index.php;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_read_timeout 60;
    }

    location ~ /\.ht {
        deny all;
    }
}
