export const THEME_TAGS = [
  'advancedPawn', 'advantage', 'anastasiaMate', 'arabianMate', 'attackingF2F7',
  'attraction', 'backRankMate', 'balestraMate', 'bishopEndgame', 'blindSwineMate',
  'bodenMate', 'capturingDefender', 'castling', 'clearance', 'collinearMove',
  'cornerMate', 'crushing', 'defensiveMove', 'deflection', 'discoveredAttack',
  'discoveredCheck', 'doubleBishopMate', 'doubleCheck', 'dovetailMate', 'enPassant',
  'endgame', 'epauletteMate', 'equality', 'exposedKing', 'fork',
  'hangingPiece', 'hookMate', 'interference', 'intermezzo', 'killBoxMate',
  'kingsideAttack', 'knightEndgame', 'long', 'master', 'masterVsMaster',
  'mate', 'mateIn1', 'mateIn2', 'mateIn3', 'mateIn4', 'mateIn5',
  'middlegame', 'morphysMate', 'oneMove', 'opening', 'operaMate',
  'pawnEndgame', 'pillsburysMate', 'pin', 'promotion', 'queenEndgame',
  'queenRookEndgame', 'queensideAttack', 'quietMove', 'rookEndgame', 'sacrifice',
  'short', 'skewer', 'smotheredMate', 'superGM', 'swallowstailMate',
  'trappedPiece', 'triangleMate', 'underPromotion', 'veryLong', 'vukovicMate',
  'xRayAttack', 'zugzwang',
];
